### ISSUE TITLE
Dataset access

### ISSUE THREAD

**Issue by ArthurOuaknine** [GiorgioMorales/MauFlex#1]
Hello.
Thanks for your interesting work.
I would like to access your dataset but the following link provided in the README and in your article doesn't work: http://didt.inictel-uni.edu.pe/dataset/MauFlex_Dataset.rar

Is your dataset still open source? Do we need to make an official request to access it?
Thanks for your answer.
Best.

**Comment by GiorgioMorales** [comment]
Hi Arthur,

Thanks for your interest. I've just checked and found that the dataset can
be downloaded from here:
http://riochili.inictel-uni.edu.pe/dataset/MauFlex_Dataset.rar.

In case it doesn't work, I just uploaded it to Sharepoint:
MauFlex_Dataset.rar
<https://montanaedu-my.sharepoint.com/:u:/g/personal/w63x712_msu_montana_edu/EU_OAZckzoFJrwGFxdY8wQUBxMNL79FU0xilawRHlKHibg?e=ErHhQp>

Bests,

Giorgio

**Comment by ArthurOuaknine** [comment]
Thanks for your reply, this new link works.
