### ISSUE TITLE
Can the data still be downloaded?

### ISSUE THREAD

**Issue by bw4sz** [GiorgioMorales/MauFlex#2]
Hello, I maintain an open source repo for tree crown delineation.

https://deepforest.readthedocs.io/en/latest/

I'd like to split your train data into individual tree segments and add to our training data. I tried to download the data but looks like the link is data. Do you have it somewhere else?

<img width="1567" alt="Screenshot 2023-11-17 at 10 39 52 AM" src="https://github.com/GiorgioMorales/MauFlex/assets/1208492/f5f5e942-719f-49b8-8664-42cddec98fcb">

**Comment by GiorgioMorales** [comment]
Thanks for letting me know. Here's a copy of the dataset: https://montanaedu-my.sharepoint.com/:u:/g/personal/w63x712_msu_montana_edu/EU_OAZckzoFJrwGFxdY8wQUBxMNL79FU0xilawRHlKHibg?e=nA0BAN

**Comment by bw4sz** [comment]
Awesome, if you know of any other datasets of Drone + crown maps or stem points in Latin America, let me know.
