### ISSUE TITLE
The dataset link is no longer available

### ISSUE THREAD

**Issue by royalgarter** [GiorgioMorales/MauFlex#3]
Where can i find the dataset for this paper?

**Comment by GiorgioMorales** [comment]
Hi, in the meantime, you can find it here: https://montanaedu-my.sharepoint.com/:u:/g/personal/w63x712_msu_montana_edu/EU_OAZckzoFJrwGFxdY8wQUBxMNL79FU0xilawRHlKHibg?e=OsES2E

**Comment by royalgarter** [comment]
Got it. Thanks for your sharing 👍
